/**
 * Membership Plans Configuration
 */

import { MembershipPlan, MembershipTier } from '@/types/membership';

export const MEMBERSHIP_PLANS: Record<MembershipTier, MembershipPlan> = {
  free: {
    tier: 'free',
    name: 'Classic',
    description: 'Perfect for occasional diners',
    monthlyPrice: 0,
    annualPrice: 0,
    annualSavings: 0,
    benefits: {
      tier: 'free',
      discountPercentage: 0,
      freeDelivery: false,
      prioritySupport: false,
      exclusiveItems: false,
      birthdayReward: 0,
      monthlyCredit: 0,
      pointsMultiplier: 1,
      earlyAccess: false,
      conciergeService: false,
      privateEvents: false,
      giftWithPurchase: false,
    },
    features: [
      'Earn 1 point per $1 spent',
      'Access to regular menu',
      'Email support',
      'Order history',
      'Standard delivery rates',
    ],
    color: '#6B7280',
    icon: 'User',
  },
  gold: {
    tier: 'gold',
    name: 'Gold',
    description: 'Enhanced experience for regular guests',
    monthlyPrice: 19.99,
    annualPrice: 199,
    annualSavings: 40,
    benefits: {
      tier: 'gold',
      discountPercentage: 10,
      freeDelivery: true,
      prioritySupport: true,
      exclusiveItems: false,
      birthdayReward: 25,
      monthlyCredit: 10,
      pointsMultiplier: 1.5,
      earlyAccess: false,
      conciergeService: false,
      privateEvents: false,
      giftWithPurchase: true,
    },
    features: [
      '10% discount on all orders',
      'Earn 1.5x points on every purchase',
      'Free delivery on all orders',
      'Priority customer support',
      '$10 monthly dining credit',
      '$25 birthday reward',
      'Monthly surprise gift',
      'Early notification of specials',
    ],
    color: '#D4AF37',
    icon: 'Star',
  },
  platinum: {
    tier: 'platinum',
    name: 'Platinum',
    description: 'Premium perks for food enthusiasts',
    monthlyPrice: 39.99,
    annualPrice: 399,
    annualSavings: 80,
    benefits: {
      tier: 'platinum',
      discountPercentage: 15,
      freeDelivery: true,
      prioritySupport: true,
      exclusiveItems: true,
      birthdayReward: 50,
      monthlyCredit: 25,
      pointsMultiplier: 2,
      earlyAccess: true,
      conciergeService: false,
      privateEvents: true,
      giftWithPurchase: true,
    },
    features: [
      '15% discount on all orders',
      'Earn 2x points on every purchase',
      'Free priority delivery',
      '24/7 priority support',
      '$25 monthly dining credit',
      '$50 birthday reward',
      'Access to exclusive menu items',
      'Early access to new dishes',
      'Invitation to exclusive events',
      'Complimentary appetizer monthly',
      'Free dessert on birthday month',
    ],
    color: '#C0C0C0',
    icon: 'Award',
  },
  diamond: {
    tier: 'diamond',
    name: 'Diamond',
    description: 'Ultimate luxury dining experience',
    monthlyPrice: 79.99,
    annualPrice: 799,
    annualSavings: 160,
    benefits: {
      tier: 'diamond',
      discountPercentage: 20,
      freeDelivery: true,
      prioritySupport: true,
      exclusiveItems: true,
      birthdayReward: 100,
      monthlyCredit: 50,
      pointsMultiplier: 3,
      earlyAccess: true,
      conciergeService: true,
      privateEvents: true,
      giftWithPurchase: true,
    },
    features: [
      '20% discount on all orders',
      'Earn 3x points on every purchase',
      'Free express delivery',
      'Dedicated concierge service',
      '$50 monthly dining credit',
      '$100 birthday reward',
      'Full access to exclusive menu',
      'First access to new dishes (48h early)',
      'VIP invitation to all events',
      'Monthly chef\'s special dish',
      'Complimentary wine pairing',
      'Private chef table reservation',
      'Annual anniversary dinner (4-course)',
      'Personalized menu recommendations',
      'Priority booking for special dates',
    ],
    color: '#B9F2FF',
    icon: 'Crown',
  },
};

// Points earning rules
export const POINTS_RULES = {
  basePointsPerDollar: 1,
  reviewBonus: 50,
  referralBonus: 100,
  firstOrderBonus: 200,
  birthdayBonus: 500,
  anniversaryBonus: 1000,
  orderStreakBonus: {
    3: 50,
    5: 100,
    10: 250,
    20: 500,
  },
  categoryCompletionBonus: 300, // Try all categories
};

// Tier upgrade thresholds (based on lifetime spending)
export const TIER_THRESHOLDS = {
  free: 0,
  gold: 0, // Can subscribe
  platinum: 0, // Can subscribe
  diamond: 0, // Can subscribe
};

// Auto-upgrade based on spending (for free users)
export const AUTO_UPGRADE_THRESHOLDS = {
  gold: 1000, // Spend $1000 lifetime to unlock gold benefits for 3 months
  platinum: 5000, // Spend $5000 lifetime to unlock platinum benefits for 3 months
  diamond: 15000, // Spend $15000 lifetime to unlock diamond benefits for 3 months
};

// Reward catalog
export const REWARDS_CATALOG = [
  {
    id: 'discount-5',
    name: '$5 Off Any Order',
    description: 'Get $5 off your next order of $25 or more',
    pointsCost: 500,
    discountAmount: 5,
    minimumTier: 'free' as MembershipTier,
    expiryDays: 30,
    available: true,
  },
  {
    id: 'discount-10',
    name: '$10 Off Any Order',
    description: 'Get $10 off your next order of $50 or more',
    pointsCost: 900,
    discountAmount: 10,
    minimumTier: 'free' as MembershipTier,
    expiryDays: 30,
    available: true,
  },
  {
    id: 'discount-20',
    name: '$20 Off Any Order',
    description: 'Get $20 off your next order of $100 or more',
    pointsCost: 1700,
    discountAmount: 20,
    minimumTier: 'gold' as MembershipTier,
    expiryDays: 30,
    available: true,
  },
  {
    id: 'free-appetizer',
    name: 'Free Appetizer',
    description: 'Choose any appetizer on us',
    pointsCost: 600,
    freeItem: 'appetizer',
    minimumTier: 'free' as MembershipTier,
    expiryDays: 30,
    available: true,
  },
  {
    id: 'free-dessert',
    name: 'Free Dessert',
    description: 'Enjoy any dessert on the house',
    pointsCost: 400,
    freeItem: 'dessert',
    minimumTier: 'free' as MembershipTier,
    expiryDays: 30,
    available: true,
  },
  {
    id: 'free-delivery',
    name: 'Free Delivery',
    description: 'Free delivery on your next order',
    pointsCost: 200,
    minimumTier: 'free' as MembershipTier,
    expiryDays: 14,
    available: true,
  },
  {
    id: 'double-points',
    name: 'Double Points Weekend',
    description: 'Earn 2x points on all orders this weekend',
    pointsCost: 1000,
    minimumTier: 'gold' as MembershipTier,
    expiryDays: 7,
    available: true,
  },
  {
    id: 'chef-special',
    name: 'Chef\'s Special Experience',
    description: 'Exclusive 5-course tasting menu',
    pointsCost: 3000,
    minimumTier: 'platinum' as MembershipTier,
    expiryDays: 60,
    available: true,
  },
];

// Spin wheel prizes configuration
export const SPIN_WHEEL_PRIZES = [
  {
    id: 'points-50',
    name: '50 Points',
    type: 'points' as const,
    value: 50,
    probability: 0.25,
    color: '#FCD34D',
    icon: 'Coins',
  },
  {
    id: 'points-100',
    name: '100 Points',
    type: 'points' as const,
    value: 100,
    probability: 0.2,
    color: '#FBBF24',
    icon: 'Coins',
  },
  {
    id: 'points-250',
    name: '250 Points',
    type: 'points' as const,
    value: 250,
    probability: 0.15,
    color: '#F59E0B',
    icon: 'Coins',
  },
  {
    id: 'discount-10',
    name: '10% Off',
    type: 'discount' as const,
    value: 10,
    probability: 0.15,
    color: '#10B981',
    icon: 'Tag',
  },
  {
    id: 'discount-15',
    name: '15% Off',
    type: 'discount' as const,
    value: 15,
    probability: 0.1,
    color: '#059669',
    icon: 'Tag',
  },
  {
    id: 'free-appetizer',
    name: 'Free Appetizer',
    type: 'freeItem' as const,
    value: 'appetizer',
    probability: 0.1,
    color: '#8B5CF6',
    icon: 'Gift',
  },
  {
    id: 'try-again',
    name: 'Try Again',
    type: 'points' as const,
    value: 0,
    probability: 0.05,
    color: '#6B7280',
    icon: 'RotateCcw',
  },
];

// Achievement definitions
export const ACHIEVEMENTS = [
  {
    id: 'first-order',
    name: 'First Taste',
    description: 'Complete your first order',
    icon: 'ShoppingBag',
    pointsReward: 100,
    requirement: { type: 'orders' as const, target: 1 },
  },
  {
    id: 'regular-customer',
    name: 'Regular Customer',
    description: 'Complete 10 orders',
    icon: 'Heart',
    pointsReward: 500,
    requirement: { type: 'orders' as const, target: 10 },
  },
  {
    id: 'loyal-patron',
    name: 'Loyal Patron',
    description: 'Complete 50 orders',
    icon: 'Award',
    pointsReward: 2000,
    requirement: { type: 'orders' as const, target: 50 },
  },
  {
    id: 'big-spender',
    name: 'Big Spender',
    description: 'Spend $1000 lifetime',
    icon: 'DollarSign',
    pointsReward: 1000,
    requirement: { type: 'spending' as const, target: 1000 },
  },
  {
    id: 'reviewer',
    name: 'Food Critic',
    description: 'Leave 10 reviews',
    icon: 'MessageSquare',
    pointsReward: 300,
    requirement: { type: 'reviews' as const, target: 10 },
  },
  {
    id: 'referrer',
    name: 'Social Butterfly',
    description: 'Refer 5 friends',
    icon: 'Users',
    pointsReward: 500,
    requirement: { type: 'referrals' as const, target: 5 },
  },
  {
    id: 'streak-7',
    name: 'Weekly Warrior',
    description: 'Order 7 days in a row',
    icon: 'Flame',
    pointsReward: 700,
    requirement: { type: 'streak' as const, target: 7 },
  },
  {
    id: 'category-master',
    name: 'Category Master',
    description: 'Try every menu category',
    icon: 'Star',
    pointsReward: 1000,
    requirement: { type: 'category' as const, target: 6 },
  },
];
