name: Deploy to GitHub Pages (Alternative)

on:
  workflow_dispatch:  # Only run manually until Pages is properly configured

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy in one job using peaceiris action as fallback
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build for GitHub Pages
        run: |
          GITHUB_PAGES=true npm run build
        env:
          NODE_ENV: production
          
      - name: Add .nojekyll file
        run: touch out/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          force_orphan: true
